# Staging Values for MCP Server .NET
global:
  registry: ghcr.io
  repository: stig-johnny/mcp-server-dotnet
  tag: "main"
  pullPolicy: Always

api:
  enabled: true
  replicaCount: 2
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi
  
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Staging"
    - name: ASPNETCORE_URLS
      value: "http://+:8080"

bff:
  enabled: true
  replicaCount: 2
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi
  
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Staging"
    - name: ASPNETCORE_URLS
      value: "http://+:8080"

gateway:
  enabled: true
  replicaCount: 2
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Staging"

# Cloudflare Tunnel Configuration for Staging
cloudflared:
  enabled: true
  replicaCount: 1
  tunnel:
    # Tunnel ID should be provided via external secret management or CI/CD
    id: "REPLACE_WITH_ACTUAL_TUNNEL_ID"
    name: "mcp-server-staging"
    ingress:
      - hostname: "mcp-staging.stigjohnny.no"
        service: "http://mcp-server-dotnet-bff.mcp-server.svc.cluster.local:80"
      - hostname: "mcp-gateway-staging.stigjohnny.no"
        service: "http://mcp-server-dotnet-gateway.mcp-server.svc.cluster.local:80"
      - hostname: "mcp-api-staging.stigjohnny.no"
        service: "http://mcp-server-dotnet-api.mcp-server.svc.cluster.local:80"
      - service: "http_status:404"
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  podDisruptionBudget:
    enabled: false  # Single replica in staging

# Note: Ingress with custom domains is disabled as it will be handled by external software
ingress:
  enabled: false
  className: "nginx"
  hosts: []
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

monitoring:
  enabled: true