# Production Values for MCP Server .NET
global:
  registry: ghcr.io
  repository: stig-johnny/mcp-server-dotnet
  tag: "v1.0.0"
  pullPolicy: Always

api:
  enabled: true
  replicaCount: 3
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"
    - name: ASPNETCORE_URLS
      value: "http://+:8080"

bff:
  enabled: true
  replicaCount: 3
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"
    - name: ASPNETCORE_URLS
      value: "http://+:8080"

# Note: Ingress with custom domains is disabled as it will be handled by external software
ingress:
  enabled: false
  className: "nginx"
  hosts: []
  tls: []

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true