apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: github-runners-dev
    app.kubernetes.io/part-of: mcp-server-dotnet
    environment: development
  finalizers:
    - resources-finalizer.argocd.argoproj.io/resource
spec:
  project: default
  source:
    repoURL: https://github.com/Stig-Johnny/mcp-server-dotnet.git
    targetRevision: develop
    path: k8s/github-runners
    kustomize:
      patchesStrategicMerge:
        - patches/development.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10