{{- if .Values.bff.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-server-dotnet.fullname" . }}-bff
  labels:
    {{- include "mcp-server-dotnet.bff.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.bff.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mcp-server-dotnet.bff.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "mcp-server-dotnet.bff.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mcp-server-dotnet.serviceAccountName" . }}
      containers:
        - name: bff
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "mcp-server-dotnet.bff.image" . }}
          imagePullPolicy: {{ .Values.bff.image.pullPolicy | default .Values.global.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.bff.service.targetPort }}
              protocol: TCP
          {{- with .Values.bff.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bff.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.bff.resources | nindent 12 }}
          env:
            {{- with .Values.bff.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- range $key, $value := .Values.config.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mcp-server-dotnet.fullname" . }}-config
            {{- if .Values.secrets.env }}
            - secretRef:
                name: {{ include "mcp-server-dotnet.fullname" . }}-secrets
            {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}