{{- if .Values.cloudflared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server-dotnet.fullname" . }}-cloudflared-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-server-dotnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudflared
  annotations:
    # This secret should be created manually or via external secret management
    # Example: kubectl create secret generic <secret-name> --from-file=credentials.json=<path-to-tunnel-credentials.json>
    description: "Cloudflare tunnel credentials - must be created manually"
type: Opaque
# Note: The secret data should be provided via external secret management or manual creation
# data:
#   credentials.json: <base64-encoded-tunnel-credentials>
{{- end }}