{{- if .Values.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server-dotnet.fullname" . }}-secrets
  labels:
    {{- include "mcp-server-dotnet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}