{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-server-dotnet.fullname" . }}-gateway
  labels:
    {{- include "mcp-server-dotnet.gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-server-dotnet.gateway.selectorLabels" . | nindent 4 }}
{{- end }}