{{- if .Values.bff.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-server-dotnet.fullname" . }}-bff
  labels:
    {{- include "mcp-server-dotnet.bff.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bff.service.type }}
  ports:
    - port: {{ .Values.bff.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-server-dotnet.bff.selectorLabels" . | nindent 4 }}
{{- end }}