name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: ${{ github.repository }}/mcp-server-api
  IMAGE_NAME_BFF: ${{ github.repository }}/mcp-server-bff
  IMAGE_NAME_HOST: ${{ github.repository }}/mcp-server-host

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Pre-restore packages on the runner to cache them
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Cache npm packages
      uses: actions/cache@v4
      with:
        path: src/Presentation/McpServer.Bff/frontend/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('src/Presentation/McpServer.Bff/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Pre-restore .NET packages
      run: dotnet restore --verbosity normal

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/Presentation/McpServer.Bff/frontend/package-lock.json

    - name: Pre-install npm packages
      run: |
        cd src/Presentation/McpServer.Bff/frontend
        npm ci --production=false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          network=host

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for API
      id: meta-api
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-

    - name: Extract metadata for BFF
      id: meta-bff
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-

    - name: Extract metadata for Host
      id: meta-host
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_HOST }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-

    - name: Build and push API Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Presentation/McpServer.Api/Dockerfile
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        network: host

    - name: Build and push BFF Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Presentation/McpServer.Bff/Dockerfile
        push: true
        tags: ${{ steps.meta-bff.outputs.tags }}
        labels: ${{ steps.meta-bff.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        network: host

    - name: Build and push Host Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Host/McpServer.Host/Dockerfile
        push: true
        tags: ${{ steps.meta-host.outputs.tags }}
        labels: ${{ steps.meta-host.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        network: host